server:
  error:
    whitelabel:
      enabled: false
    path: /error

auth:
  access-token-expired-hours: 1
  refresh-token-expired-hours: 720
  jwt-secret-key:

thread-pool:
  history:
    size: 3
    max-size: 30
    queue-capacity: 100